### ISSUE TITLE
Find a way to host reveal.js slideshows

### ISSUE THREAD

**Issue by niksirbi** [neuroinformatics-unit/software-skills#21]
It would be nice to host reveal.js slideshows (like [this one](https://neuroinformatics-unit.github.io/swc-hpc-pose-estimation/#/title-slide)) here and link them to their corresponding courses.
Would be a user-friendly way for students to come back and review the materials.

**Comment by adamltyson** [comment]
+1 for this, it would also be useful to host Rob's iPython slides.
