### ISSUE TITLE
Come up with a good default home page

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/software-skills#25]
Currently cards are displayed for upcoming  courses. What should go on the front page if there are no upcoming courses?

Maybe just some cards of previously run cards? If so, should we have two sections? Something like:

------
## SWC/GCNU Software Skills

Computational skills training at the [UCL](https://www.ucl.ac.uk/) [Sainsbury Wellcome Centre](https://www.sainsburywellcome.org/web/) and [Gatsby Computational Neuroscience Unit](https://www.ucl.ac.uk/gatsby/gatsby-computational-neuroscience-unit).

### Upcoming courses
| Some upcoming course  | 
| :---  |         
| Dates |       
| Details   |

### Previous courses
| Some previous course  | 
| :---  |         
| Details   |

------

**Comment by adamltyson** [comment]
Any ideas @neuroinformatics-unit/website-team?

**Comment by JoeZiminski** [comment]
I think this is a good pattern. If there are no upcoming courses, can the 'upcoming courses' section be flattened so only the previous courses are shown (and maybe somehting like more courses coming soon...). Not sure of the overhead of implementing though.

**Comment by adamltyson** [comment]
TBH we could just comment it out if there aren't any upcoming courses.
